### ISSUE TITLE
Support task on Linux Agents

### ISSUE THREAD

**Issue by tylercranston** [dependency-check/azuredevops#55] opened 2020-11-06 10:17 UTC
- Dependency Check task currently is only supported on Windows Agents
- Feature requested to support Linux Agents

**Comment by ejohn20** [comment] 2020-11-08 22:12
Duplicate of #23. Open to PRs here, all of our builds are running on Windows agents, so it's unlikely this will happen any time soon.

**Closed by ejohn20** 2020-11-08 22:12 UTC
